#!/bin/bash
# ior.pbs
#   Invoke ior with typical arguments and default environment
# vlaues



#PBS -l nodes=2:ppn=16
#PBS -l walltime=00:05:00
#PBS -A dr002
#PBS -N NS_FPS
#PBS -m bea
#PBS -M sid.kashyap@ed.ac.uk
#PBS -q devel

module load gcc/4.8.2
module load openmpi/gcc/64/1.4.5    
  

TARGET="/scratch/dr002/shared/IOR_DiRAC/NS.FPS"
IOR="/scratch/dr002/shared/DiRAC3-testsuite/bin/ior"
IOR_SCRIPT="/scratch/dr002/shared/IOR_DiRAC/NS.FPS/con.ior"

date '+%Y%m%d%H%M%S'

pushd $TARGET
rm -rf testDir
mkdir testDir;

numNodes=(  2 )
blockSize=( 16 )

for test in `seq 1` 
do 
    test=$(( $test - 1 ))
    mpirun -np ${numNodes[$test]} -pernode /scratch/dr002/shared/IOR_DiRAC/NS.FPS/code1.sh  -vvv  -b ${blockSize[$test]}g -f $IOR_SCRIPT
done
popd
