#!/bin/tcsh

set TARGET="/cosma5/data/dr002/dc-kash1/IOR_DiRAC/NS.FPS"
set IOR="/cosma5/data/dr002/dc-kash1/ior/bin/ior"
set IOR_SCRIPT="$TARGET/con.ior"

date '+%Y%m%d%H%M%S'

pushd $TARGET

set numNodes = (1)
echo $numNodes[1]
set blockSize = (32)
echo $blockSize[1]

foreach test (`seq 1`)
    set cmd="$IOR -vvv  -b ${blockSize[$test]}g -f $IOR_SCRIPT"
    echo "mpirun -np $numNodes[$test] -ppn 1 $IOR -vvv  -b $blockSize[$test]g -f $IOR_SCRIPT"
    mpirun -np $numNodes[$test] -ppn 1 $IOR -vvv  -b $blockSize[$test]g -f $IOR_SCRIPT
end
popd


