#!/bin/tcsh

#BSUB -n 1
#BSUB -x
#BSUB -R "span[ptile=1]"
#BSUB -J NW_SHF_HDF5
#BSUB -o NW_SHF_HDF5.out.%J
#BSUB -e NW_SHF_HDF5.err.%J
#BSUB -q cosma5
#BSUB -P dr002
#BSUB -W 00:10
 
  
set TARGET="/cosma5/data/dr002/dc-kash1/IOR_DiRAC/NW.SHF"
set IOR="/cosma5/data/dr002/dc-kash1/ior/bin/ior"
set IOR_SCRIPT="$TARGET/con.ior"


date '+%Y%m%d%H%M%S'

pushd $TARGET


setenv  LD_LIBRARY_PATH /cosma5/data/dr002/dc-kash1/hdf5-1.8.15-patch1/lib:$LD_LIBRARY_PATH
setenv  LD_RUN_PATH /cosma5/data/dr002/dc-kash1/hdf5-1.8.15-patch1/lib:$LD_RUN_PATH
setenv  LDFLAGS "-L/cosma5/data/dr002/dc-kash1/hdf5-1.8.15-patch1/lib"


setenv HDF5_DISABLE_VERSION_CHECK 1

set numNodes= ( 1 )
set blockSize= ( 16 )

foreach test (`seq 1`)
    mpirun -np $numNodes[$test]  $IOR -vvv  -b $blockSize[$test]m -f $IOR_SCRIPT
end
popd

