#!/bin/bash
# ior.pbs
#   Invoke ior with typical arguments and default environment
# vlaues



#PBS -l select=1
#PBS -l walltime=00:10:00
#PBS -A d63
#PBS -N test
#PBS -m bea
#PBS -M sid.kashyap@ed.ac.uk
 
  


module swap PrgEnv-cray PrgEnv-intel
module swap intel intel/15.0.2.164
module load cray-hdf5-parallel/1.8.13

TARGET="/work/d63/d63/shared/IOR_DiRAC_HDF5/test"
IOR="/work/d63/d63/skashyap/sid/ior_install/ior_intel_dyn/ior/ior_build/bin/ior"
IOR_SCRIPT="/work/d63/d63/shared/IOR_DiRAC_HDF5/test/con.ior"

date '+%Y%m%d%H%M%S'
pushd $TARGET

numNodes=(  1 )
blockSize=( 512 )

for test in `seq 1` 
do 
    test=$(( $test - 1 ))
    cmd="$IOR -vvv  -b ${blockSize[$test]}g -f $IOR_SCRIPT"
    aprun -n ${numNodes[$test]} -N 1 $IOR -vvv  -b ${blockSize[$test]}m -f $IOR_SCRIPT
done
popd


